In [2]:
import numpy as np

In [3]:
# creation of numpy array

x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# shape and size
print(x.size)  ## total number of elements
print(x.shape) # dimensions
print(x.ndim)

5
(5,)
1


In [5]:
x2d=np.array([[1,2,3],[4,5,6]])
print(x2d)
print(x2d.size)  ## total number of elements
print(x2d.shape) # dimensions
print(x2d.ndim)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [6]:
x25=np.random.randint(1,100,(5,5)) #1=lowest value,100=highest value,(5,5)=size of matrix
print(x25)

[[70 19 84 96 21]
 [ 1 33 81 40 76]
 [ 6 86 36 39 58]
 [ 7 89 55 73 44]
 [34 81 82 65  5]]


In [7]:
xseq1=np.arange(1,101,4)   #4=gap between numbers
print(xseq1)
print(xseq1.size)
print(xseq1.reshape(5,5))

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


In [19]:
xseq2=np.linspace(1,100,50)  #50 = no of elements
print(xseq2)
print(xseq2.size)
print(xseq2.reshape(5,5,2))

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
50
[[[  1.           3.02040816]
  [  5.04081633   7.06122449]
  [  9.08163265  11.10204082]
  [ 13.12244898  15.14285714]
  [ 17.16326531  19.18367347]]

 [[ 21.20408163  23.2244898 ]
  [ 25.24489796  27.26530612]
  [ 29.28571429  31.30612245]
  [ 33.32653061  35.34693878]
  [ 37.36734694  39.3877551 ]]

 [[ 41.40816327  43.42857143]
  [

In [9]:
xseq2d=xseq2.reshape(10,5)
print(xseq2d)

NameError: name 'xseq2' is not defined

In [10]:
np.ones((2,5),dtype="int") ## by defauklt if dtype not given then its float

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## indeing and slicing
## boolean filter
## maths and stuff
## methods

In [11]:
x25


array([[70, 19, 84, 96, 21],
       [ 1, 33, 81, 40, 76],
       [ 6, 86, 36, 39, 58],
       [ 7, 89, 55, 73, 44],
       [34, 81, 82, 65,  5]])

In [12]:
## first row
print(x25[0])

[70 19 84 96 21]


In [13]:
print(x25[-1])

[34 81 82 65  5]


In [14]:
print(x25[0,1])

19


In [15]:
## coloumn no 1
print(x25[:,0])

## coloumn no 1
print(x25[:,-1])



[70  1  6  7 34]
[21 76 58 44  5]


In [16]:
## coloumn 0 and 1 indx
print(x25[:,[0,1,2]]) ## all rows and 0 1 2 coloumn

print(x25[:,3]) ## all rows 3 coloumn

[[70 19 84]
 [ 1 33 81]
 [ 6 86 36]
 [ 7 89 55]
 [34 81 82]]
[96 40 39 73 65]


In [17]:
print(x25[:4,[0,1]])

[[70 19]
 [ 1 33]
 [ 6 86]
 [ 7 89]]


In [43]:
print(x25[:2,[2,4]])

[[33 73]
 [25 71]
 [60  2]]


In [18]:
print(x25[:,[0,1,2,4]])

[[70 19 84 21]
 [ 1 33 81 76]
 [ 6 86 36 58]
 [ 7 89 55 44]
 [34 81 82  5]]


In [19]:
print(x25[1:3])

[[ 1 33 81 40 76]
 [ 6 86 36 39 58]]


In [51]:
x25

array([[28, 88, 33, 27, 73],
       [84, 11, 25, 44, 71],
       [90,  8, 60, 46,  2],
       [83, 17, 15, 99, 64],
       [18, 62, 61, 54, 82]])

In [20]:
# filter data without boolean filter
for i in x25:
    
    for j in i:
        if j<20:
            print(j)

19
1
6
7
5


In [21]:
x25<=20  ## boolean filter


array([[False,  True, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False,  True]])

In [22]:
x25[x25<=20]

array([19,  1,  6,  7,  5])

In [23]:
x25[(x25>20) & (x25<50)]

array([21, 33, 40, 36, 39, 44, 34])

In [24]:
np.append

<function numpy.append(arr, values, axis=None)>

In [25]:
np.append(x25,[1,2,3,4,5]) ## not s expectedd but works

array([70, 19, 84, 96, 21,  1, 33, 81, 40, 76,  6, 86, 36, 39, 58,  7, 89,
       55, 73, 44, 34, 81, 82, 65,  5,  1,  2,  3,  4,  5])

In [26]:
np.append(x25,np.array([[1,2,3,4,5]]),axis=0)

array([[70, 19, 84, 96, 21],
       [ 1, 33, 81, 40, 76],
       [ 6, 86, 36, 39, 58],
       [ 7, 89, 55, 73, 44],
       [34, 81, 82, 65,  5],
       [ 1,  2,  3,  4,  5]])

In [29]:
a=np.random.randint(1,100,(3,2))
b=np.random.randint(1,100,(2,3))
print(a)

[[79  2]
 [54 92]
 [54 44]]


## transpose matrix first then stack horizontally and vertically

In [40]:
a.transpose()



array([[79, 54, 54],
       [ 2, 92, 44]])

In [44]:
print(np.hstack((a,b.T)))


[[79  2 84 90]
 [54 92 40 55]
 [54 44 72 78]]


In [49]:
print(np.hstack((a.T,b)))

[[79 54 54 84 40 72]
 [ 2 92 44 90 55 78]]


In [46]:
print(np.vstack((a,b.T)))


[[79  2]
 [54 92]
 [54 44]
 [84 90]
 [40 55]
 [72 78]]


In [31]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print()
print(y)


[[8 3 9]
 [6 5 8]
 [2 7 3]]

[[8 3 7]
 [8 8 2]
 [7 4 7]]


In [51]:
print(x.dot(y))
print()
print(x.prod(1))
print()

[[151  84 125]
 [144  90 108]
 [ 93  74  49]]

[216 240  42]



In [35]:
print(x.mean())
print(x.mean(axis=0)) #row
print(x.mean(axis=1))#colo


5.666666666666667
[5.33333333 5.         6.66666667]
[6.66666667 6.33333333 4.        ]


In [36]:
print(x.max())
print(x.min())
print(x.argmax())# index of max value
print(x.argmin())# index of min value
print(x.flatten()[4]) # accessing the index value given by argmax()

9
2
2
6
5


In [38]:
np.median(x) # some functions are calledd using np,if available through the variable

6.0